added User and Role
Ilya-brinchuk/bank-service pull request #1
Opened 2021-02-26 16:39 UTC by Ilya-brinchuk

2021-02-28 15:20 UTC, YuraBondarenko approved these changes

2021-03-01 10:24 UTC, KseniiaMakarova requested changes

2021-03-01 10:24 UTC, KseniiaMakarova commented on pom.xml
> +        </dependency>
do we need this dependency?

2021-03-01 10:24 UTC, KseniiaMakarova commented on src/main/java/bankservice/demo/controller/DataInitializer.java
> +    private UserService userService;
```suggestion
    private final RoleService roleService;
    private final UserService userService;
```

2021-03-01 10:24 UTC, KseniiaMakarova commented on src/main/java/bankservice/demo/exception/DataProcessingException.java
> +
redundant empty line

2021-03-01 10:24 UTC, KseniiaMakarova commented on src/main/java/bankservice/demo/repository/RoleRepository.java
> +    Optional<Role> getRoleByRoleName(@Param("name") String name);
```suggestion
    Optional<Role> getByRoleName(Role.RoleName name);
```
Spring Data JPA is capable of automatically build the query in many cases based on the method name and parameters)

2021-03-01 10:24 UTC, KseniiaMakarova commented on src/main/java/bankservice/demo/repository/UserRepository.java
> +    Optional<User> findUserByPhoneNumber(@Param(value = "number") String number);
```suggestion
    Optional<User> findById(Long id);

    @Query("select u from users u inner join fetch u.roles where u.phoneNumber = :number")
    Optional<User> findByPhoneNumber(String number);
```

we can simplify this a bit

2021-03-01 10:24 UTC, KseniiaMakarova commented on src/main/java/bankservice/demo/service/UserService.java
> +    User update(User user);
see checklist

2021-03-01 10:24 UTC, KseniiaMakarova commented on src/main/java/bankservice/demo/service/UserService.java
> +    User findUserByPhoneNumber(String phoneNumber);
```suggestion
    User getByPhoneNumber(String phoneNumber);
```

2021-03-01 12:10 UTC, KseniiaMakarova requested changes

2021-03-01 12:10 UTC, KseniiaMakarova commented on src/main/java/bankservice/demo/repository/UserRepository.java
> +    Optional<User> findById(Long id);
you need to join fetch roles here as well - that was right
I meant that we can remove `@Param` annotation

2021-03-01 12:10 UTC, KseniiaMakarova commented on src/main/java/bankservice/demo/service/RoleService.java
> +    Role getByName(Role.RoleName roleName);
you should not change this method
on the service level we get String - and RoleName on the dao layer

2021-03-01 13:14 UTC, KseniiaMakarova approved these changes

2021-03-01 13:14 UTC, KseniiaMakarova commented on src/main/java/bankservice/demo/controller/DataInitializer.java
> +        System.out.println(roleService.getByName("ADMIN"));
great, we may remove this)

2021-03-01 13:27 UTC, merged